version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: crud
      MYSQL_ROOT_PASSWORD: vini123
      MYSQL_USER: vini
      MYSQL_PASSWORD: vini123
    ports:
      - 3306:3306